
SchemaVersion: '1.0'
SageMaker:
  PythonSDK:
    Modules:
      RemoteFunction:
        Dependencies: './requirements.txt'
        EnableInterContainerTrafficEncryption: true
        EnvironmentVariables: {'EnvVarKey': 'EnvVarValue'}
        IncludeLocalWorkDir: true
        CustomFileFilter: 
          IgnoreNamePatterns:
            - "*.ipynb"
            - "data"
            - "__pycache__"
        InstanceType: 'ml.m5.large'
        JobCondaEnvironment: 'python'
